### ISSUE TITLE
load file from command line

### ISSUE THREAD

**Issue by mhenry1384** [JonathanAquino/git-time-lapse-view#1]
This is great, the thing I miss most from my years of using Perforce.

Only one thing - could you add the ability to load a file from the command-line? 
I would like to be able to right click on a file in Windows explorer and send it to the application.

**Comment by JonathanAquino** [comment]
You should be able to do this now, because we check the command-line arguments for a filename: https://github.com/JonathanAquino/git-time-lapse-view/blob/master/src/com/jonathanaquino/gittimelapseview/Application.java#L30

It's been a while since I have done that, so I can't tell you exactly how to do it. Let me know if you find out.
